# Generated by Django 5.2.7 on 2025-11-05 06:55

import CBC_App.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('typical_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='CBC_App.canonicaltest')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_raw', models.CharField(blank=True, max_length=100)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='CBC_App.canonicaltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('generated_by', models.CharField(default='rules_engine_v1', max_length=100)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation', to='CBC_App.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_value_raw', models.CharField(blank=True, max_length=100)),
                ('previous_value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('new_value_raw', models.CharField(blank=True, max_length=100)),
                ('new_value_numeric', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('corrected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_logs', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='CBC_App.testresult')),
            ],
        ),
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=CBC_App.models.upload_to_report)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_test_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='CBC_App.uploaddocument'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('full_name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
